### ISSUE TITLE
hook failed: "certificates-relation-joined" when private ppa is not configured

### ISSUE THREAD

**Issue by davecore82** [narindergupta/kafka-charm#4]
I deploy the kafka charm but the juju status is `error hook failed: "certificates-relation-joined"`. 

The juju log unit-kafka-0.log shows the following:

```
2021-03-10 13:28:34 DEBUG certificates-relation-joined Traceback (most recent call last):
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "/var/lib/juju/agents/unit-kafka-0/charm/hooks/certificates-relation-joined", line 22, in <module>
2021-03-10 13:28:34 DEBUG certificates-relation-joined     main()
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "/var/lib/juju/agents/unit-kafka-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 74, in main
2021-03-10 13:28:34 DEBUG certificates-relation-joined     bus.dispatch(restricted=restricted_mode)
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "/var/lib/juju/agents/unit-kafka-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
2021-03-10 13:28:34 DEBUG certificates-relation-joined     _invoke(other_handlers)
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "/var/lib/juju/agents/unit-kafka-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
2021-03-10 13:28:34 DEBUG certificates-relation-joined     handler.invoke()
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "/var/lib/juju/agents/unit-kafka-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
2021-03-10 13:28:34 DEBUG certificates-relation-joined     self._action(*args)
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "/var/lib/juju/agents/unit-kafka-0/charm/reactive/tls.py", line 165, in import_ca_crt_to_keystore
2021-03-10 13:28:34 DEBUG certificates-relation-joined     '-storepass', keystore_password(),
2021-03-10 13:28:34 DEBUG certificates-relation-joined   File "lib/charms/layer/kafka.py", line 227, in keystore_password
2021-03-10 13:28:34 DEBUG certificates-relation-joined     os.open(path, os.O_WRONLY | os.O_CREAT, 0o440),
2021-03-10 13:28:34 DEBUG certificates-relation-joined FileNotFoundError: [Errno 2] No such file or directory: '/etc/kafka/keystore.secret'
2021-03-10 13:28:34 ERROR juju.worker.uniter.operation runhook.go:132 hook "certificates-relation-joined" failed: exit status 1
```

After speaking with Narinder, the problem is that I don't have the PPA necessary to install the Kafka packages. 

```
root@node08ob32:/var/log/juju# apt-cache policy kafka
N: Unable to locate package kafka
```

Ideally I think the charm should verify if access to the kafka packages is available or should fail during the attempt to install Kafka before giving an error about the certificates-relation-joined hook failure.

**Comment by davecore82** [comment]
My workaround is to attach an Ubuntu Advantage UA Apps subscription and juju resolve the unit, I'm on Ubuntu 18.04:

```
ubuntu@kubeflow-demo:~$ juju ssh kafka/0

ubuntu@node08ob32:~$ sudo add-apt-repository ppa:canonical-server/ua-client-daily
ubuntu@node08ob32:~$ sudo apt install ubuntu-advantage-tools
ubuntu@node08ob32:~$ sudo ua attach <my token from https://ubuntu.com/advantage>
ubuntu@node08ob32:~$ apt-cache policy kafka
kafka:
  Installed: (none)
  Candidate: 2.2.2u1-0ubuntu1+esm2
  Version table:
     2.2.2u1-0ubuntu1+esm2 500
        500 https://esm.ubuntu.com/apps/ubuntu bionic-apps-security/main amd64 Packages
ubuntu@node08ob32:~$ logout

ubuntu@kubeflow-demo:~$ juju resolve kafka/0
ubuntu@kubeflow-demo:~/kubeflow-demo/infrastructure/kubeflow$ juju status kafka
Model  Controller             Cloud/Region       Version  SLA          Timestamp
kafka  maas_cloud_controller  orangebox/default  2.7.8    unsupported  13:45:53Z

App    Version  Status  Scale  Charm  Store       Rev  OS      Notes
kafka  2.2.2u1  active      1  kafka  jujucharms   30  ubuntu  
ntp    3.2      active      1  ntp    jujucharms   45  ubuntu  

Unit      Workload  Agent  Machine  Public address  Ports     Message
kafka/0*  active    idle   0        172.27.33.55    9093/tcp  ready
  ntp/1   active    idle            172.27.33.55    123/udp   chrony: Ready

Machine  State    DNS           Inst id     Series  AZ       Message
0        started  172.27.33.55  node08ob32  bionic  default  Deployed
```
